server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_ENDPOINT}:5432/postgres
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    properties:
      hibernate:
        default_batch_fetch_size: 500
        show_sql: true
        format_sql: true
