server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/yugioh
    username: yugioh
    password: yugioh
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    properties:
      hibernate:
        default_batch_fetch_size: 500
        show_sql: true
        format_sql: true
